server:
  port: 8080

management:
  port: ${server.port}
  context-path: /admin
  info.git.mode: full
  security.enabled: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

###
# Logging Configuration
###
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: ERROR
    com.example: INFO
  file: ./log/application.log

spring:
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dicksa974/ef-ref-config.git

---
spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
    fetch-registry: false

---
spring:
  profiles: local

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true